#ifndef _LANG_H_
#define _LANG_H_

#define ELFNAME		"Master.elf"
#define COPYRIGHT	"Master.elf\n(c) BingK(binghelingxi)\n(r) all the author of CfgEdit!"

//#define LANG_CN
//#define LANG_EN

#ifdef LANG_CN

#define ERR_STR			"ґнОу!"
#define LGP_EXIT		"АлїЄ"
#define LGP_SELECT		"СЎФс"
#define LGP_MENU		"ІЛµҐ"
#define LGP_OPTIONS		"СЎПо"
#define LGP_ONOFF		"їЄ/№Ш"
#define LGP_QUIT		"НЛіц"
#define LGP_ABOUT		"№ШУЪ..."
#define LGP_NOTSUPPORT	"І»Ц§іЦµДМхДї"
#define LGP_ENTER		"ЅшИл"
#define LGP_CBOX_ERR	"ґнОуµДСЎПо"
#define LGP_OK			"НкіЙ"
#define	LGP_BACK		"·µ»Ш"
#define LGP_CLOSE		"№Ш±Х"
#define LGP_SELECT_FILE	"СЎФсОДјю"
#define LGP_SELECT_FOLDER	"СЎФсОДјюјР"
#define LGP_PROFILE		"Зйѕ°ДЈКЅ"
/*#define LGP_PROFILE1	"Зйѕ°ДЈКЅ1"
#define LGP_PROFILE2	"Зйѕ°ДЈКЅ2"
#define LGP_PROFILE3	"Зйѕ°ДЈКЅ3"
#define LGP_PROFILE4	"Зйѕ°ДЈКЅ4"
#define LGP_PROFILE5	"Зйѕ°ДЈКЅ5"
#define LGP_PROFILE6	"Зйѕ°ДЈКЅ6"
#define LGP_PROFILE7	"Зйѕ°ДЈКЅ7"*/
#define LGP_DEL_ALL		"ЗеіэЛщУРЕдЦГ"
#define LGP_RELOAD_CONFIG_ERR	"ЦШРВ¶БИЎЕдЦГК§°Ь!"
#define LGP_DEL_THIS	"ЗеіэёГІ№¶ЎЕдЦГ"
#define LGP_DEL_UNUSED	"ЗеіэОЮУГЕдЦГ"
#define LGP_PATCH_NAME	"І№¶Ў:"
#define LGP_PATCH_AUTHOR	"ЧчХЯ:"
#define LGP_PATCH_ID	"ID:"
#define LGP_PATCH_VERSION	"°ж±ѕ:"
#define LGP_PATCH_INFO_OTH	"ЖдЛьРЕПў:"
#define LGP_PATCH_INFO	"І№¶ЎРЕПў"
#define LGP_BACKUP		"±ё·ЭЕдЦГ"
#define LGP_RESTORE		"»Цёґ±ё·Э"
#define LGP_BACKUP_PATH "±ё·ЭОДјюВ·ѕ¶:"
#define LGP_RESTORE_PATH	"»Цёґ±ё·ЭВ·ѕ¶:"
#define LGP_ENTER_PATH	"КдИлОДјюјРВ·ѕ¶"
#define LGP_IS_OFF		"ТС№Ш±Х"
#define	LGP_QUIT_WITHOUT_RS	"І»ЛўРВMPНЛіц"
#endif

#ifdef LANG_EN

#define ERR_STR			"Error!"
#define LGP_EXIT		"Exit"
#define LGP_SELECT		"Select"
#define LGP_MENU		"Menu"
#define LGP_OPTIONS		"Options"
#define LGP_ONOFF		"On/Off"
#define LGP_QUIT		"Quit"
#define LGP_ABOUT		"About..."
#define LGP_NOTSUPPORT	"ItemNotSupported"
#define LGP_ENTER		"Enter"
#define LGP_CBOX_ERR	"ChoiceIndexError!"
#define LGP_OK			"OK"
#define	LGP_BACK		"Back"
#define LGP_CLOSE		"Close"
#define LGP_SELECT_FILE	"Select File"
#define LGP_SELECT_FOLDER	"Select Folder"
#define LGP_PROFILE		"Profile"
/*#define LGP_PROFILE1	"Profile1"
#define LGP_PROFILE2	"Profile2"
#define LGP_PROFILE3	"Profile3"
#define LGP_PROFILE4	"Profile4"
#define LGP_PROFILE5	"Profile5"
#define LGP_PROFILE6	"Profile6"
#define LGP_PROFILE7	"Profile7"*/
#define LGP_DEL_ALL		"Clear All Configs"
#define LGP_RELOAD_CONFIG_ERR	"Reload Config Error!"
#define LGP_DEL_THIS	"Clear This Config"
#define LGP_DEL_UNUSED	"Clear Unused Configs"
#define LGP_PATCH_NAME	"Name:"
#define LGP_PATCH_AUTHOR	"Author:"
#define LGP_PATCH_ID	"ID:"
#define LGP_PATCH_VERSION	"Version:"
#define LGP_PATCH_INFO_OTH	"Other Info:"
#define LGP_PATCH_INFO	"Info"
#define LGP_BACKUP		"Backup Configs"
#define LGP_RESTORE		"Restore Configs"
#define LGP_BACKUP_PATH "Backup Path:"
#define LGP_RESTORE_PATH	"Restore Path:"
#define LGP_ENTER_PATH	"Enter Folder Path"
#define LGP_IS_OFF		"Is Off"
#define	LGP_QUIT_WITHOUT_RS	"Quit Without RunScaner"
#endif

#ifdef LANG_RU      //By Tonich

#define ERR_STR			"Ошибка!"
#define LGP_EXIT		"Выход"
#define LGP_SELECT		"Выбор"
#define LGP_MENU		"Меню"
#define LGP_OPTIONS		"Опции"
#define LGP_ONOFF		"Вкл/Выкл"
#define LGP_QUIT		"Выйти"
#define LGP_ABOUT		"О проге..."
#define LGP_NOTSUPPORT	"Не поддерживаемый элемент"
#define LGP_ENTER		"Открыть"
#define LGP_CBOX_ERR	"Ошибка смены индекса!"
#define LGP_OK			"OK"
#define	LGP_BACK		"Назад"
#define LGP_CLOSE		"Закрыть"
#define LGP_SELECT_FILE	"Выбрать файл"
#define LGP_SELECT_FOLDER	"Выбрать папку"
#define LGP_PROFILE		"Профиль"
/*#define LGP_PROFILE1	"Profile1"
#define LGP_PROFILE2	"Profile2"
#define LGP_PROFILE3	"Profile3"
#define LGP_PROFILE4	"Profile4"
#define LGP_PROFILE5	"Profile5"
#define LGP_PROFILE6	"Profile6"
#define LGP_PROFILE7	"Profile7"*/
#define LGP_DEL_ALL		"Сбросить все конфиги"
#define LGP_RELOAD_CONFIG_ERR	"Ошибка обновления конфига!"
#define LGP_DEL_THIS	"Сбросить этот конфиг"
#define LGP_DEL_UNUSED	"Сбросить неиспользуемые конфиги"
#define LGP_PATCH_NAME	"Название:"
#define LGP_PATCH_AUTHOR	"Автор:"
#define LGP_PATCH_ID	"ID:"
#define LGP_PATCH_VERSION	"Версия:"
#define LGP_PATCH_INFO_OTH	"Дополнительно:"
#define LGP_PATCH_INFO	"Информация"
#define LGP_BACKUP		"Сделать бекап конфигов"
#define LGP_RESTORE		"Восстановить из бекапа"
#define LGP_BACKUP_PATH "Бекапить в:"
#define LGP_RESTORE_PATH	"Восстанавливать в:"
#define LGP_ENTER_PATH	"Выберите путь до папки"
#define LGP_IS_OFF		"Выключен?"
#define	LGP_QUIT_WITHOUT_RS	"Выити без RunScaner-а"
#endif

#endif
